language: java
dist: trusty
os: osx
jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true

before_install:
#  - mvn install -Dmaven.javadoc.skip=true
   - "echo skipped"
install:
  - "echo skipped"
script:
#  - "echo skipped"
  - mvn clean install -Dmaven.javadoc.skip=true
  - mvn test
# - mvn deploy
notifications:
  email:
    recipients:
      - 411316753@qq.com
    #on_success: [always|never|change]  default: change
    #on_failure: [always|never|change]  default: always

